### PR TITLE
Issue/#6

### LINKED ISSUE #6: Open Notificaties makes unwarrented use of a volume
Open Notificaties doesn't need a volume as there is no need for storage.

### PR DESCRIPTION
**Pull request by andyverberne**
Fixes #6 
remove unwarrented use of volume in Open Notificaties deployment

### CODE REVIEW

**Comment by sergei-maertens** [comment]
@andyverberne  #5  was merged, can you resolve the merge conflict and/or rebase this PR?

**Comment by andyverberne** [comment]
My perception is that everything is correct now.

**Comment by sergei-maertens** [comment]
Not quite I think - looking at https://github.com/open-zaak/charts/blob/main/charts/open-notificaties/templates/pvc.yaml there is still a PVC being created for ON which isn't needed. I think this PR was supposed to remove the PVC aspect from ON?

**Comment by andyverberne** [comment]
You are right. However I do not know how to deal with this merge conflict. I will create a separate pull request to remove the vollume from ON

**Pull request closed without merging**
